version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing Hugo...
      - apt-get install hugo
      - BUILD_NUMBER=$(date +%Y%m%d-%H%M%S)
      - VERSION=1.0.$BUILD_NUMBER
      - echo Build version is $VERSION
  build:
    commands:
      - echo Build started on `date`
      - echo Running Hugo publish...
      - hugo
      - echo Running publish.sh
      - SKIP_CONFIRM=true ./publish.sh
  post_build:
    commands:
      - echo Build completed on `date`