version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Installing Hugo...
      - export HUGO_VERSION="0.96.0"
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
      - dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
      - BUILD_NUMBER=$(date +%Y%m%d-%H%M%S)
      - VERSION=1.0.$BUILD_NUMBER
      - echo Build version is $VERSION
  build:
    commands:
      - echo Build started on `date`
      - echo Running Hugo publish...
      - hugo
      - echo Running publish.sh
      - SKIP_CONFIRM=true ./publish.sh
  post_build:
    commands:
      - echo Build completed on `date`