version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing Hugo...
      - export HUGO_VERSION="0.111.3"
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb
      - dpkg -i hugo_${HUGO_VERSION}_linux-amd64.deb
      - BUILD_NUMBER=$(date +%Y%m%d-%H%M%S)
      - VERSION=1.0.$BUILD_NUMBER
      - echo Build version is $VERSION
      - npm install
      - echo Node dependencies installed
  build:
    commands:
      - echo Build started on `date`
      - echo Running Hugo publish...
      - hugo
      - echo Running publish.sh
      - chmod +x ./publish.sh
      - SKIP_CONFIRM=true ./publish.sh
  post_build:
    commands:
      - echo Build completed on `date`
